version: "3.0"

services:
  webserver:
    image: flashspys/nginx-static
    container_name: webserver
    ports:
      - 8080:80
    volumes: 
      - ./static-files:/static

networks:
  app_network:
    driver: bridge
